issue configuration pull requests:
  title: 'Issue configuration pull requests'
  restrict access: true

administer configuration pull request:
  title: 'Administer Config Pull Request'
  restrict access: true
