services:
  config_pr.repo_controller:
    class: Drupal\config_pr\RepoController
    tags:
      - { name: service_collector, tag: config_pr.repo_controller, call: addController }

  config_pr.repo_controller.github:
    class: Drupal\config_pr\RepoControllers\GithubController
    tags:
      - { name: config_pr.repo_controller }

  config_pr.repo_controller.gitlab:
    class: Drupal\config_pr\RepoControllers\GitlabController
    tags:
      - { name: config_pr.repo_controller }
