services:
#  config_pr.repo_controller_collector:
#    class: Drupal\config_pr\RepoControllerCollector
#    tags:
#      - { name: service_collector, call: addRepoController, tag: config_pr.repo_controller }

  config_pr.github_controller:
    class: Drupal\config_pr\RepoControllers\GithubController
    parent: default_plugin_manager
    tags:
      -  { name: config_pr.repo_controller }

  config_pr.repo_manager:
    class: Drupal\config_pr\Repo\RepoManager
    tags:
      - { name: service_collector, tag: config_pr.repo_provider, call: addProvider }

  config_pr.repo_provider.github:
    class: Drupal\config_pr\Repo\GithubProvider
    tags:
      - { name: config_pr.repo_provider }

  config_pr.repo_provider.gitlab:
    class: Drupal\config_pr\Repo\GitlabProvider
    tags:
      - { name: config_pr.repo_provider }
