name: 'Config Pull Request GitLab Support'
type: module
description: 'BitBucket controller for Config Pull Request module.'
package: Administration
version: VERSION
core: 8.x
configure: config_pr.settings
dependencies:
  - config_pr:config_pr
